// src-react/components/customers/Customers.tsx
import React, { useState, lazy, Suspense } from 'react';
import styled from 'styled-components';
import { Link } from '@tanstack/react-router';
import { useQuery } from '@tanstack/react-query';

import { ICustomer, IPagedResults } from '../../interfaces';
import FilterTextbox from '../shared/FilterTextbox';
import CustomersCard from './CustomersCard';
import CustomersGrid from './CustomersGrid';
import Pagination from '../shared/Pagination';

const Map = lazy(() => import('../shared/Map'));

const CustomersView = styled.div`
  padding: 20px;
`;

const Container = styled.div`
  width: 100%;
  padding-right: 15px;
  padding-left: 15px;
  margin-right: auto;
  margin-left: auto;
  
  @media (min-width: 576px) {
    max-width: 540px;
  }
  
  @media (min-width: 768px) {
    max-width: 720px;
  }
  
  @media (min-width: 992px) {
    max-width: 960px;
  }
  
  @media (min-width: 1200px) {
    max-width: 1140px;
  }
`;

const Header = styled.header`
  margin-bottom: 20px;
`;

const Title = styled.h3`
  margin-bottom: 0;
  font-weight: 500;
  line-height: 1.2;
`;

const Icon = styled.span`
  margin-right: 10px;
`;

const Row = styled.div`
  display: flex;
  flex-wrap: wrap;
  margin-right: -15px;
  margin-left: -15px;
`;

const Column = styled.div`
  position: relative;
  width: 100%;
  padding-right: 15px;
  padding-left: 15px;
  
  @media (min-width: 768px) {
    flex: 0 0 83.333333%;
    max-width: 83.333333%;
  }
`;

const NavBar = styled.div`
  margin-bottom: 20px;
`;

const NavList = styled.ul`
  display: flex;
  flex-wrap: wrap;
  padding-left: 0;
  margin-bottom: 0;
  list-style: none;
`;

const NavItem = styled.li`
  margin-right: 10px;
`;

const NavLink = styled.a<{ active?: boolean }>`
  display: block;
  padding: 0.5rem 1rem;
  text-decoration: none;
  color: ${props => props.active ? '#007bff' : '#6c757d'};
  background-color: ${props => props.active ? '#f8f9fa' : 'transparent'};
  border-radius: 0.25rem;
  cursor: pointer;
  
  &:hover {
    color: #007bff;
    background-color: #e9ecef;
  }
`;

const RouterNavLink = styled(Link)`
  display: block;
  padding: 0.5rem 1rem;
  text-decoration: none;
  color: #6c757d;
  border-radius: 0.25rem;
  
  &:hover {
    color: #007bff;
    background-color: #e9ecef;
  }
`;

const FilterContainer = styled.div`
  display: flex;
  justify-content: flex-end;
  margin-left: auto;
`;

const MapContainer = styled.div`
  width: 100%;
  height: 400px;
  margin-bottom: 20px;
`;

const useLogger = () => {
  const log = (message: any) => {
    console.log(message);
  };
  
  return { log };
};

const useFilterService = () => {
  const filter = <T extends object>(items: T[], data: string, props: string[]): T[] => {
    return items.filter(item => {
      let match = false;
      for (const prop of props) {
        const value = getPropValue(item, prop);
        if (value && value.toString().toUpperCase().indexOf(data) > -1) {
          match = true;
          break;
        }
      }
      return match;
    });
  };
  
  const getPropValue = (obj: any, path: string): any => {
    return path.split('.').reduce((prev, curr) => {
      return prev ? prev[curr] : null;
    }, obj);
  };
  
  return { filter };
};

enum DisplayModeEnum {
  Card = 0,
  Grid = 1,
  Map = 2
}

const Customers: React.FC = () => {
  const [displayMode, setDisplayMode] = useState<DisplayModeEnum>(DisplayModeEnum.Card);
  const [filterText, setFilterText] = useState<string>('');
  const [currentPage, setCurrentPage] = useState<number>(1);
  const pageSize = 10;
  
  const { log } = useLogger();
  const { filter } = useFilterService();
  
  const { data, isLoading, error } = useQuery<IPagedResults<ICustomer>>({
    queryKey: ['customers', currentPage, pageSize],
    queryFn: async () => {
      const response = await fetch(`/api/customers/page/${(currentPage - 1) * pageSize}/${pageSize}`);
      if (!response.ok) {
        throw new Error('Failed to fetch customers');
      }
      const data = await response.json();
      log(`getCustomersPage() retrieved customers for page: ${currentPage}`);
      return data;
    }
  });
  
  const customers = data?.results || [];
  const totalRecords = data?.totalRecords || 0;
  
  const filteredCustomers = React.useMemo(() => {
    if (filterText && customers.length) {
      const upperFilter = filterText.toUpperCase();
      const props = ['firstName', 'lastName', 'city', 'state.name'];
      return filter(customers, upperFilter, props);
    }
    return customers;
  }, [customers, filterText, filter]);
  
  const handleDisplayModeChange = (mode: DisplayModeEnum) => {
    setDisplayMode(mode);
  };
  
  const handleFilterChange = (text: string) => {
    setFilterText(text);
  };
  
  const handlePageChange = (page: number) => {
    setCurrentPage(page);
  };
  
  if (isLoading) {
    return <Container>Loading customers...</Container>;
  }
  
  if (error) {
    return <Container>Error loading customers</Container>;
  }
  
  return (
    <CustomersView className="customers view indent">
      <Container>
        <Header>
          <Title>
            <Icon className="glyphicon glyphicon-user"></Icon>
            Customers
          </Title>
        </Header>
        <br />
        
        <Row>
          <Column>
            <NavBar className="navbar">
              <NavList className="nav navbar-nav">
                <NavItem className="toolbar-item">
                  <NavLink 
                    onClick={() => handleDisplayModeChange(DisplayModeEnum.Card)}
                    active={displayMode === DisplayModeEnum.Card}
                  >
                    <Icon className="glyphicon glyphicon-th-large"></Icon> Card View
                  </NavLink>
                </NavItem>
                <NavItem className="toolbar-item">
                  <NavLink 
                    onClick={() => handleDisplayModeChange(DisplayModeEnum.Grid)}
                    active={displayMode === DisplayModeEnum.Grid}
                  >
                    <Icon className="glyphicon glyphicon-align-justify"></Icon> List View
                  </NavLink>
                </NavItem>
                <NavItem className="toolbar-item">
                  <NavLink 
                    onClick={() => handleDisplayModeChange(DisplayModeEnum.Map)}
                    active={displayMode === DisplayModeEnum.Map}
                  >
                    <Icon className="glyphicon glyphicon-map-marker"></Icon> Map View
                  </NavLink>
                </NavItem>
                <NavItem className="toolbar-item">
                  <RouterNavLink to="/customers/0/edit">
                    <Icon className="glyphicon glyphicon-plus"></Icon> New Customer
                  </RouterNavLink>
                </NavItem>
              </NavList>
              <FilterContainer className="navbar-right">
                <FilterTextbox onFilterChange={handleFilterChange} />
              </FilterContainer>
            </NavBar>
          </Column>
        </Row>
        
        {displayMode === DisplayModeEnum.Card && (
          <CustomersCard customers={filteredCustomers} />
        )}
        
        {displayMode === DisplayModeEnum.Grid && (
          <CustomersGrid customers={filteredCustomers} />
        )}
        
        {displayMode === DisplayModeEnum.Map && (
          <MapContainer>
            <Suspense fallback={<div>Loading map...</div>}>
              <Map 
                zoom={2}
                enabled={true}
                dataPoints={filteredCustomers.map(customer => ({
                  latitude: customer.latitude || 0,
                  longitude: customer.longitude || 0,
                  firstName: customer.firstName,
                  lastName: customer.lastName,
                  markerText: `<h3>${customer.firstName} ${customer.lastName}</h3>`
                }))}
              />
            </Suspense>
          </MapContainer>
        )}
        
        <Pagination 
          totalItems={totalRecords}
          pageSize={pageSize}
          onPageChange={handlePageChange}
        />
      </Container>
    </CustomersView>
  );
};

export default Customers;

// src/app/customers/customers.component.ts
import { Component } from '@angular/core';
import { ROUTER_DIRECTIVES } from '@angular/router';
//import { Observable } from 'rxjs/Observable';

import { DataService } from '../shared/services/data.service';
import { FilterTextboxComponent } from '../filterTextbox/filterTextbox.component';
import { CustomersCardComponent } from './customersCard.component';
import { CustomersGridComponent } from './customersGrid.component'
import { ICustomer, IOrder } from '../shared/interfaces';

@Component({ 
  moduleId: module.id,
  selector: 'customers', 
  templateUrl: 'customers.component.html',
  directives: [ROUTER_DIRECTIVES, FilterTextboxComponent, 
               CustomersCardComponent, CustomersGridComponent]
})
export class CustomersComponent {

  title: string;
  filterText: string;
  customers: ICustomer[] = [];
  filteredCustomers: ICustomer[] = [];
  displayMode: DisplayModeEnum;
  displayModeEnum = DisplayModeEnum;

  constructor(private dataService: DataService) { }
  
  ngOnInit() {
    this.title = 'Customers';
    this.filterText = 'Filter Customers:';
    this.displayMode = DisplayModeEnum.Card;

    this.dataService.getCustomers()
        .subscribe((customers: ICustomer[]) => {
          this.customers = this.filteredCustomers = customers;
        });

  }

  changeDisplayMode(mode: DisplayModeEnum) {
      this.displayMode = mode;
  }

  filterChanged(data: string) {
    if (data && this.customers) {
        data = data.toUpperCase();
        let props = ['firstName', 'lastName', 'address', 'city', 'orderTotal'];
        let filtered = this.customers.filter(item => {
            let match = false;
            for (let prop of props) {
                //console.log(item[prop] + ' ' + item[prop].toUpperCase().indexOf(data));
                if (item[prop].toString().toUpperCase().indexOf(data) > -1) {
                  match = true;
                  break;
                }
            };
            return match;
        });
        this.filteredCustomers = filtered;
    }
    else {
      this.filteredCustomers = this.customers;
    }
  }

}

enum DisplayModeEnum {
  Card = 0,
  Grid = 1,
  Map = 2
}

<div class="customers-page">
        <div class="page-header">
            <div class="header-content">
                <h1 class="page-title">{{ title }}</h1>
                <p class="page-subtitle">Manage your customer relationships</p>
            </div>
            <div class="header-actions">
                <a routerLink="/customers/0/edit" class="btn btn-primary">
                    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <circle cx="12" cy="12" r="10"/>
                        <line x1="12" y1="8" x2="12" y2="16"/>
                        <line x1="8" y1="12" x2="16" y2="12"/>
                    </svg>
                    New Customer
                </a>
            </div>
        </div>

        <div class="page-toolbar">
            <div class="view-options">
                <button 
                    class="view-btn"
                    [class.active]="displayMode === displayModeEnum.Card"
                    (click)="changeDisplayMode(displayModeEnum.Card)"
                    title="Card View">
                    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <rect x="3" y="3" width="7" height="7"/>
                        <rect x="14" y="3" width="7" height="7"/>
                        <rect x="14" y="14" width="7" height="7"/>
                        <rect x="3" y="14" width="7" height="7"/>
                    </svg>
                    Cards
                </button>
                <button 
                    class="view-btn"
                    [class.active]="displayMode === displayModeEnum.Grid"
                    (click)="changeDisplayMode(displayModeEnum.Grid)"
                    title="List View">
                    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <line x1="8" y1="6" x2="21" y2="6"/>
                        <line x1="8" y1="12" x2="21" y2="12"/>
                        <line x1="8" y1="18" x2="21" y2="18"/>
                        <line x1="3" y1="6" x2="3.01" y2="6"/>
                        <line x1="3" y1="12" x2="3.01" y2="12"/>
                        <line x1="3" y1="18" x2="3.01" y2="18"/>
                    </svg>
                    List
                </button>
                <button 
                    class="view-btn"
                    [class.active]="displayMode === displayModeEnum.Map"
                    (click)="lazyLoadMapComponent()"
                    title="Map View">
                    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <polygon points="1,6 1,22 8,18 16,22 23,18 23,2 16,6 8,2"/>
                        <line x1="8" y1="2" x2="8" y2="18"/>
                        <line x1="16" y1="6" x2="16" y2="22"/>
                    </svg>
                    Map
                </button>
            </div>
            <div class="toolbar-search">
                <cm-filter-textbox (changed)="filterChanged($event)"></cm-filter-textbox>
            </div>
        </div>
        
        <cm-customers-card 
          [customers]="filteredCustomers" 
          (customerDeleted)="deleteCustomer($event)"
          [hidden]="displayMode !== displayModeEnum.Card"></cm-customers-card>
    
        <cm-customers-grid 
          [customers]="filteredCustomers" 
          [hidden]="displayMode !== displayModeEnum.Grid"></cm-customers-grid>

        <!-- lazy load the map component -->
        <div [hidden]="displayMode !== displayModeEnum.Map">
            <ng-container #mapsContainer></ng-container>
        </div>

        <!-- 
            This could be used to eagerly load the map component.
            Would need to import MapModule into either SharedModule (and export it) or 
            into CustomersModule to use it this way.
        -->
        <!-- <cm-map *ngIf="filteredCustomers.length" 
            [zoom]="2" 
            [enabled]="displayMode === displayModeEnum.Map" 
            [hidden]="displayMode !== displayModeEnum.Map">
          <cm-map-point 
            *ngFor="let customer of filteredCustomers" 
            [latitude]="customer.latitude" 
            [longitude]="customer.longitude"
            [markerText]="'<h3>' + customer.firstName + ' ' + customer.lastName + '</h3>' + customer.city + ', ' + customer.state.name"></cm-map-point>
        </cm-map> -->

        <cm-pagination
            [totalItems]="totalRecords" 
            [pageSize]="pageSize" 
            (pageChanged)="pageChanged($event)"></cm-pagination>
          
</div>
