// src-react/components/shared/Pagination.tsx
import React, { useState, useEffect, MouseEvent } from 'react';
import styled from 'styled-components';

const PaginationNav = styled.nav``;

const PaginationList = styled.ul`
  display: flex;
  padding-left: 0;
  list-style: none;
  border-radius: 0.25rem;
`;

const PaginationItem = styled.li<{ active?: boolean; disabled?: boolean }>`
  position: relative;
  display: block;
  padding: 0.5rem 0.75rem;
  margin-left: -1px;
  line-height: 1.25;
  color: #007bff;
  background-color: #fff;
  border: 1px solid #dee2e6;
  cursor: ${props => (props.disabled ? 'not-allowed' : 'pointer')};
  
  &:first-child {
    margin-left: 0;
    border-top-left-radius: 0.25rem;
    border-bottom-left-radius: 0.25rem;
  }
  
  &:last-child {
    border-top-right-radius: 0.25rem;
    border-bottom-right-radius: 0.25rem;
  }
  
  ${props => props.active && `
    z-index: 1;
    color: #fff;
    background-color: #027FF4;
    border-color: #027FF4;
  `}
  
  ${props => props.disabled && `
    color: #6c757d;
    pointer-events: none;
    background-color: #fff;
    border-color: #dee2e6;
  `}
`;

const PaginationLink = styled.a`
  cursor: pointer;
`;

interface PaginationProps {
  pageSize: number;
  totalItems: number;
  onPageChange: (page: number) => void;
}

const Pagination: React.FC<PaginationProps> = ({ 
  pageSize, 
  totalItems, 
  onPageChange 
}) => {
  const [currentPage, setCurrentPage] = useState(1);
  const [pages, setPages] = useState<number[]>([]);
  const [isVisible, setIsVisible] = useState(false);
  const [previousEnabled, setPreviousEnabled] = useState(false);
  const [nextEnabled, setNextEnabled] = useState(true);
  const [totalPages, setTotalPages] = useState(0);

  useEffect(() => {
    if (pageSize && totalItems) {
      const calculatedTotalPages = Math.ceil(totalItems / pageSize);
      setTotalPages(calculatedTotalPages);
      setIsVisible(true);
      
      if (totalItems >= pageSize) {
        const newPages = [];
        for (let i = 1; i <= calculatedTotalPages; i++) {
          newPages.push(i);
        }
        setPages(newPages);
      }
    } else {
      setIsVisible(false);
    }
  }, [pageSize, totalItems]);

  const handlePreviousNext = (direction: number, event?: React.MouseEvent) => {
    if (event) {
      event.preventDefault();
    }
    
    let page = currentPage;
    if (direction === -1) {
      if (page > 1) { page--; }
    } else {
      if (page < totalPages) { page++; }
    }
    
    changePage(page, event);
  };

  const changePage = (page: number, event?: React.MouseEvent) => {
    if (event) {
      event.preventDefault();
    }
    
    if (currentPage === page) { return; }
    
    setCurrentPage(page);
    setPreviousEnabled(page > 1);
    setNextEnabled(page < totalPages);
    onPageChange(page);
  };

  if (!isVisible) {
    return null;
  }

  return (
    <PaginationNav>
      <PaginationList className="pagination">
        <PaginationItem 
          disabled={!previousEnabled} 
          onClick={(e) => handlePreviousNext(-1, e)}
        >
          <PaginationLink aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </PaginationLink>
        </PaginationItem>
        
        {pages.map(page => (
          <PaginationItem 
            key={page} 
            active={currentPage === page} 
            onClick={(e) => changePage(page, e)}
          >
            <PaginationLink>{page}</PaginationLink>
          </PaginationItem>
        ))}
        
        <PaginationItem 
          disabled={!nextEnabled} 
          onClick={(e) => handlePreviousNext(1, e)}
        >
          <PaginationLink aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </PaginationLink>
        </PaginationItem>
      </PaginationList>
    </PaginationNav>
  );
};

export default Pagination;

// src/app/shared/pagination/pagination.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'cm-pagination',
  templateUrl: './pagination.component.html',
  styleUrls: [ './pagination.component.css' ]
})

export class PaginationComponent implements OnInit {

  private pagerTotalItems = 0;
  private pagerPageSize = 0;

  totalPages = 0;
  pages: number[] = [];
  currentPage = 1;
  isVisible = false;
  previousEnabled = false;
  nextEnabled = true;

  @Input() get pageSize(): number {
    return this.pagerPageSize;
  }

  set pageSize(size: number) {
    this.pagerPageSize = size;
    this.update();
  }

  @Input() get totalItems(): number {
    return this.pagerTotalItems;
  }

  set totalItems(itemCount: number) {
    this.pagerTotalItems = itemCount;
    this.update();
  }

  @Output() pageChanged: EventEmitter<number> = new EventEmitter();

  constructor() { }

  ngOnInit() {

  }

  update() {
    if (this.pagerTotalItems && this.pagerPageSize) {
      this.totalPages = Math.ceil(this.pagerTotalItems / this.pageSize);
      this.isVisible = true;
      if (this.totalItems >= this.pageSize) {
        for (let i = 1; i < this.totalPages + 1; i++) {
          this.pages.push(i);
        }
      }
      return;
    }

    this.isVisible = false;
  }

  previousNext(direction: number, event?: MouseEvent) {
    let page: number = this.currentPage;
    if (direction === -1) {
        if (page > 1) { page--; }
    } else {
        if (page < this.totalPages) { page++; }
    }
    this.changePage(page, event);
  }

  changePage(page: number, event?: MouseEvent) {
    if (event) {
      event.preventDefault();
    }
    if (this.currentPage === page) { return; }
    this.currentPage = page;
    this.previousEnabled = this.currentPage > 1;
    this.nextEnabled = this.currentPage < this.totalPages;
    this.pageChanged.emit(page);
  }

}

<nav [hidden]="!isVisible">
  <ul class="pagination">
    <li [class.disabled]="!previousEnabled" (click)="previousNext(-1, $event)">
      <a aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    @for (page of pages; track page) {
        <li (click)="changePage(page, $event)" [class.active]="currentPage === page">
          <a>{{ page }}</a>
        </li>
    }
    <li [class.disabled]="!nextEnabled" (click)="previousNext(1, $event)">
      <a aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>
